title: "My Personal Website"
theme: pages-themes/slate@v0.2.0
description: "A showcase of my projects, articles, and expertise."
# For the navigation bar
header_pages:
  - index.md
  - projects.md
  - articles.md
