title: "Bowen Kruse"
theme: minima
description: "A website for my resume and articles that should probably be published elsewhere"
# For the navigation bar
header_pages:
  - index.md
  - projects.md
  - articles.md
